---
collections:
  - name: community.general
  - name: servicenow.itsm
  # - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
  - name: ansible.eda
  - name: infra.aap_configuration