---
- name: Linux server patching
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  vars:
    report_server: reports

  tasks:

  - name: Run only succeeded hosts
    when: patch_progress[inventory_hostname].status == 'success'
    block:

      - name: Include patching role
        ansible.builtin.include_role:
          name: demo.patching.patch_linux

      - name: Set Success Status
        ansible.builtin.set_fact:
          patch_progress:
            status: success
            step: apply_patchig
          
      - name: Set_Stats Success Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_overal_status: "success"

    rescue:
      - name: Set Fail Status
        ansible.builtin.set_fact:
          patch_progress:
            status: fail
            step: apply_patchig

      - name: Set_Stats Fail Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_overal_status: "unsuccessful"
        failed_when: true
