---
- name: Linux server patching
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  vars:
    report_server: reports

  tasks:

  - name: Run only succeeded hosts
    when: patch_progress[inventory_hostname] == 'success'
    block:

      - name: Include patching role
        ansible.builtin.include_role:
          name: demo.patching.patch_linux

      - name: Set Success Status
        ansible.builtin.set_fact:
          patch_progress:
            - key: "{{ inventory_hostname }}"
              value: 'success'
          patch_stage:
            - key: "{{ inventory_hostname }}"
              value: apply_patching
        
      - name: Set_Stats Success Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_stage: "{{ patch_stage | items2dict }}"

    rescue:
      - name: Set Failure Status
        ansible.builtin.set_fact:
          patch_progress:
            - key: "{{ inventory_hostname }}"
              value: 'fail'
          patch_stage:
            - key: "{{ inventory_hostname }}"
              value: apply_patching
        
      - name: Set_Stats Failure Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_stage: "{{ patch_stage | items2dict }}"

      - name: Set Change Close Status
        ansible.builtin.set_stats:
          data:
            cr_close_status: unsuccessful
          aggregate: no
        failed_when: true

