---
- name: Linux server Post patching
  hosts: "{{ _hosts | default(omit) }}"
  become: true

  tasks:
    # Install yum-utils if it's not there
    - name: Install yum-utils
      ansible.builtin.yum:
        name: yum-utils
        state: installed
