---
- name: Linux server Post patching
  hosts: "{{ _hosts | default(omit) }}"
  become: true

  tasks:
    # Post Patch Task
    - name: Print Message
      ansible.builtin.debug:
        msg: "Post Tasks after patching"
        