---
- name: Post Application Tasks
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  vars:
    app_role_name: "demo.application.{{ app_deployment }}"

  tasks:

  - name: Run only succeeded hosts
    when: patch_progress.status == 'success'
    block:
      - name: Post Patch | Verify {{ app_deployment }} Application
        ansible.builtin.include_role:
          name: "{{ app_role_name }}"
          tasks_from: test.yml

      - name: Set Success Status
        ansible.builtin.set_fact:
          patch_progress:
            status: success
            step: post_app_tasks
          cacheable: yes

    rescue:
      - name: Set Fail Status
        ansible.builtin.set_fact:
          patch_progress:
            status: fail
            step: post_app_tasks
          cacheable: yes
        failed_when: true


