---
- name: Linux server Post patching
  hosts: "{{ _hosts | default(omit) }}"
  become: true

  tasks:
  
  - name: Run only succeeded hosts
    when: patch_progress[inventory_hostname] == 'success'
    block:
      # Post Patch Task
      - name: Print Message
        ansible.builtin.debug:
          msg: "Post Tasks after patching"

      - name: Set Successful Status
        ansible.builtin.set_fact:
          patch_progress:
            - key: "{{ inventory_hostname }}"
              value: 'success'
          patch_stage:
            - key: "{{ inventory_hostname }}"
              value: post_patch_tasks
        
      - name: Set_Stats Successful Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_stage: "{{ patch_stage | items2dict }}"
            patch_overal_status: "successful"

    rescue:
      - name: Set Failure Status
        ansible.builtin.set_fact:
          patch_progress:
            - key: "{{ inventory_hostname }}"
              value: 'fail'
          patch_stage:
            - key: "{{ inventory_hostname }}"
              value: post_patch_tasks
        
      - name: Set_Stats Failure Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_stage: "{{ patch_stage | items2dict }}"
            patch_overal_status: "unsuccessful"
        failed_when: true

        