---
- name: Linux server Post patching
  hosts: "{{ _hosts | default(omit) }}"
  become: true

  tasks:
  
  - name: Run only succeeded hosts
    when: patch_progress[inventory_hostname].status == 'success'
    block:
      # Post Patch Task
      - name: Print Message
        ansible.builtin.debug:
          msg: "Post Tasks after patching"

      - name: Set Success Status
        set_fact:
          patch_progress:
            status: success
            step: post_patch_tasks

      - name: Set_Stats Success Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_overal_status: "success"

    rescue:
      - name: Set Fail Status
        set_fact:
          patch_progress:
            status: fail
            step: post_patch_tasks

      - name: Set_Stats Fail Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_overal_status: "unsuccessful"
        failed_when: true

        