---
- name: Post Application Tasks
  hosts: "{{ _hosts | default(omit) }}"
  become: true

  tasks:

    - name: Post Patch | Verify {{ app_deployment }} Application
      ansible.builtin.include_role:
        name: "{{ app_role_name }}"
        tasks_from: test.yml
