---
- name: Pre Application Tasks
  hosts: "{{ _hosts | default(omit) }}"
  become: true

  vars:
    app_role_name: "demo.application.{{ app_deployment }}"

  tasks:

  - name: Run only succeeded hosts
    when: patch_progress[inventory_hostname].status == 'success'
    block:
      - name: Pre Patch | Verify {{ app_deployment }} Application
        ansible.builtin.include_role:
          name: "{{ app_role_name }}"
          tasks_from: test.yml

      - name: Pre Patch | Stop {{ app_deployment }} Application
        ansible.builtin.include_role:
          name: "{{ app_role_name }}"
          tasks_from: stop_service.yml
      
      - name: Set Successful Status
        ansible.builtin.set_fact:
          patch_progress:
            - key: "{{ inventory_hostname }}"
              value: 'success'
          patch_stage:
            - key: "{{ inventory_hostname }}"
              value: pre_patch_tasks
        
      - name: Set_Stats Successful Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_stage: "{{ patch_progress | items2dict }}"
            patch_overal_status: "successful"

    rescue:
      - name: Set Failure Status
        ansible.builtin.set_fact:
          patch_progress:
            - key: "{{ inventory_hostname }}"
              value: 'fail'
          patch_stage:
            - key: "{{ inventory_hostname }}"
              value: pre_app_tasks
        
      - name: Set_Stats Failure Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_stage: "{{ patch_progress | items2dict }}"
            patch_overal_status: "unsuccessful"
        failed_when: true
