---
- name: Linux server Pre patching
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  gather_facts: yes

  tasks:

  - name: Run only succeeded hosts
    when: patch_progress[inventory_hostname].status == 'success'
    block:
      - name: Pre Patch | Include role for Pre Tasks
        ansible.builtin.include_role:
          name: demo.patching.patch_linux
          tasks_from: pre_task.yml

      - name: Set Success Status
        set_fact:
          patch_progress:
            status: success
            step: pre_patch_tasks

      - name: Set_Stats Success Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_overal_status: "success"

    rescue:
      - name: Set Fail Status
        set_fact:
          patch_progress:
            status: fail
            step: pre_patch_tasks

      - name: Set_Stats Fail Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_progress | items2dict }}"
            patch_overal_status: "unsuccessful"
        failed_when: true
