---
- name: Linux server Pre patching
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  gather_facts: yes

  tasks:

    - name: Pre Patch | Include role for Pre Tasks
      ansible.builtin.include_role:
        name: demo.patching.patch_linux
        tasks_from: pre_task.yml