---
- name: Pre Application Tasks
  hosts: "{{ _hosts | default(omit) }}"
  become: true

  vars:
    app_role_name: "demo.application.{{ app_deployment }}"

  tasks:

  - name: Run only succeeded hosts
    when: patch_progress.status == 'success'
    block:
      - name: Pre Patch | Verify {{ app_deployment }} Application
        ansible.builtin.include_role:
          name: "{{ app_role_name }}"
          tasks_from: test.yml

      - name: Pre Patch | Stop {{ app_deployment }} Application
        ansible.builtin.include_role:
          name: "{{ app_role_name }}"
          tasks_from: stop_service.yml
      
      - name: Set Success Status
        set_fact:
          patch_progress:
            status: success
            step: pre_app_task
          cacheable: yes

    rescue:
      - name: Set Fail Status
        set_fact:
          patch_progress:
            status: fail
            step: pre_app_task
          cacheable: yes
        failed_when: true


      