---
- name: Creating VM Snapshot
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false
  connection: local

  tasks:

  - name: Run only succeeded hosts
    when: patch_progress[inventory_hostname] == 'success'
    block:
      - name: Include Cloud role
        ansible.builtin.include_role:
          name: demo.cloud.aws
          tasks_from: snapshot_vm

      - name: Set Successful Status
        ansible.builtin.set_fact:
          patch_prog:
            - key: "{{ inventory_hostname }}"
              value: 'success'
          patch_stg:
            - key: "{{ inventory_hostname }}"
              value: snapshot_create
        
      - name: Set_Stats Successful Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_prog | items2dict }}"
            patch_stage: "{{ patch_stg | items2dict }}"

    rescue:
      - name: Set Failure Status
        ansible.builtin.set_fact:
          patch_prog:
            - key: "{{ inventory_hostname }}"
              value: 'fail'
          patch_stg:
            - key: "{{ inventory_hostname }}"
              value: snapshot_create
        
      - name: Set_Stats Failure Status
        ansible.builtin.set_stats:
          data:
            patch_progress: "{{ patch_prog | items2dict }}"
            patch_stage: "{{ patch_stg | items2dict }}"

      - name: Set Change Close Status
        ansible.builtin.set_stats:
          data:
            cr_close_status: unsuccessful
          aggregate: no
        failed_when: true
