---
- name: Creating VM Snapshot
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false
  connection: local

  tasks:

    - name: Include Cloud role
      ansible.builtin.include_role:
        name: demo.cloud.aws
        tasks_from: snapshot_vm_delete
