---
- name: Create an incident in ServiceNow using facts from a host
  hosts: "{{ vm_name | default('all')}}"
  gather_facts: false
  connection: local

  pre_tasks:
  - name: Set variables
    ansible.builtin.set_fact:
      ervicenow_ticket: create
      incident_description: >-
        Patch has been failed with the following servers
        {{ failed_hosts }}
    vars:
      failed_hosts: |-
        {% for host in groups['all'] %} {{ host if ( patch_progress[host] == 'fail' ) }} at {{ patch_stage[host] }} stage {% endfor %}
      
    run_once: yes

  roles:
    - demo.process.snow_ticket
  run_once: yes
