---
- name: Close a change request
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    servicenow_cr: close
    close_code: "successful if {{ close_code }}"
    close_notes: "{{ close_notes }}"

  roles:
    - demo.process.snow_change_request
  run_once: yes