---
- name: Set Default variables
  hosts: all
  gather_facts: false
  tasks:
    - name: Set Default Status
      ansible.builtin.set_fact:
        patch_progress:
          - key: "{{ inventory_hostname }}"
            value: 'success'
        patch_stage:
          - key: "{{ inventory_hostname }}"
            value: Start
      
    - name: Set_Stats Successful Status
      ansible.builtin.set_stats:
        data:
          patch_progress: "{{ patch_progress | items2dict }}"
          patch_stage: "{{ patch_stage | items2dict }}"

    - name: Set Change Close Status
      ansible.builtin.set_stats:
        data:
          cr_close_status: successful
        aggregate: no

- name: Create a change request and send Slack Notification
  hosts: all
  gather_facts: false
  connection: local

  vars:
    servicenow_cr: CR_Slack_Wait
    cr_short_description: "Patch Change Request"
    cr_description: "{{ change_owner | default('Ansible') }} requests {{ groups['all'] }} servers in {{ change_environment | default('Dev') }} to patch"

  roles:
    - demo.process.snow_change_request
  run_once: yes


