---
- name: AWS | SNAPSHOT VM
  delegate_to: localhost
  block:

    - name: AWS | SNAPSHOT VM | delete snapshots
      amazon.aws.ec2_snapshot:
        region: "{{ aws_region }}"
        snapshot_id: "{{ aws_snapshots[inventory_hostname].snapshot_id }}"
        state: absent

