---
- name: AWS | SNAPSHOT VM
  delegate_to: localhost
  block:
    - name: AWS | SNAPSHOT VM | assert id
      ansible.builtin.assert:
        that: instance_id is defined
        fail_msg: "instance_id is required for snapshot operations"

    - name: AWS | SNAPSHOT VM | include vars
      ansible.builtin.include_vars:
        file: snapshot_vm.yml

    - name: AWS | SNAPSHOT VM | get volumes
      register: r_vol_info
      amazon.aws.ec2_vol_info:
        region: "{{ aws_region }}"
        filters:
          attachment.instance-id: "{{ instance_id }}"

    - name: AWS | SNAPSHOT VM | delete snapshots
      loop: "{{ r_vol_info.volumes }}"
      loop_control:
        loop_var: volume
        label: "{{ volume.id }}"
      register: r_snapshots
      amazon.aws.ec2_snapshot:
        region: "{{ aws_region }}"
        snapshot_id: "{{ volume.snapshot_id }}"
        state: absent
