---
controller_credentials:
  - name: "ServiceNow Credential"
    organization: "Default"
    credential_type: "ServiceNow"
    inputs:
      instance_id: "{{ snow_hostname }}"
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
 
  - name: "AWS Snapshot Credential"
    organization: "Default"
    credential_type: "Amazon Web Services"
    inputs:
      username: "{{ aws_access_key }}"
      password: "{{ aws_secret_key }}"
 
  - name: "Slack Notification Credential"
    organization: "Default"
    credential_type: "Slack"
    inputs:
      token: "{{ slack_token }}"
 
controller_notifications:
  - name: "Patching Slack Notifications"
    organization: "Default"
    notification_type: slack
    notification_configuration:
      token: "{{ slack_token }}"
      channels:
        - "#patching-notifications"