controller_credential_types:
  - name: "ServiceNow"
    description: !unsafe ''
    kind: "cloud"
    inputs:
      fields:
      - id: instance_id
        type: string
        label: Instance
      - id: username
        type: string
        label: Username
      - id: password
        type: string
        label: Password
        secret: true
      required:
      - instance_id
      - username
      - password

    injectors:
      env:
        SN_HOST: !unsafe '{{instance_id}}'
        SN_PASSWORD: !unsafe '{{password}}'
        SN_USERNAME: !unsafe '{{username}}'

  - name: "Slack"
    description: !unsafe ''
    kind: "cloud"
    inputs:
      fields:
      - id: token
        type: string
        label: Token
        secret: true
      required:
      - token

    injectors:
      env:
        SLACK_TOKEN: !unsafe '{{token}}'